
# QMB3302 Foundations of Analytics and AI {.unnumbered}

| **Instructor**          | **Contact**                             | **Class**                 | **Information**                  |
|-------------------------|-----------------------------------------|---------------------------|----------------------------------|
| **Instructor:**         | Dr. Joel Davis                           | **Class Location:**       | NA                               |
| **Email:**              | joeldavis@ufl.edu                        | **Class Day/Time:**       | NA                               |
| **Office Hours:**       | W 1-3. See detail below                  | **Web:**                  | [https://ufl.instructure.com](https://ufl.instructure.com) |
| **Location:**    | Stuzin 100, Retail Center                |                           |                                  |
| **Phone:**       | 352-273-3292                             |                           |                                  |
| **Term:**               | Summer 2025                                |                           |                                  |


# COURSE DETAILS {.unnumbered}

## Welcome to the course!

This course is designed to introduce you to the basics of data analytics and machine learning using the powerful programming language Python. No prior programming experience is required. The course is structured into two main sections. Students will first learn the basics of Python and how to write programs in Weeks 1-6. Weeks 6+ progress to using Python to solve real world analytical problems.

Why learn Python? Python is rapidly becoming the language of choice fordata scientists, data analysts, and those working on cutting edge business analytics. It is the tool of choice for this work at companies such as Google,Amazon, Facebook, IBM, NASA, Accenture, and Deloitte. It is also free to use, making it widely available to firms and users around the world. Beyond business analytics, Python is often used as a general programming language to automate tasks. 

Why learn machine learning? Businesses today often use data to solve complex problems. A business that ignores the data it generates is at a significant disadvantage. The skills required to analyze and interpret that data are in short supply. A basic understanding of Artificial Intelligence and how it is used in business will be critical for tomorrows business leaders. Regardless of the domain a student decides to work in after graduation, it is likely that AI skills will make them more competitive in the job market.

## COURSE OBJECTIVES

- **_Programming:_** Install Python and Jupyter notebooks
- **_Programming:_** Read basic Python programs, recognizing the structures and patterns within, and be able to explain how they work
- **_Programming:_** Write and run Python scripts to manipulate, clean, and prepare data for analysis
- **_Programming:_** Debug and problem solve coding errors
- **_Analytics:_** Produce basic visualizations using standard Python libraries
- **_Analytics:_** Produce basic statistical summaries of continuous and categorical data
- **_Artificial Intelligence:_** Understand the different AI models and approaches businesses use
- **_Artificial Intelligence:_** Build a simple machine learning model
- **_Applied Analytics and AI:_** Understand how Python and other business analytics programs can be used in business applications

## PREREQUISITES

For relevant course prerequisites, please refer to [one.uf](https://one.uf.edu).

This course is suitable for those with no programming experience.

## COMPUTER AND SOFTWARE

The notebooks assume a Python 3 installation with the standard modules from an Anaconda installation, such as Numpy and Matplotlib. Students should use the Anaconda distribution of Python on a Windows or Macintosh PC. The download and all required software is free. Although UF APPS has the required software, a local installation is strongly preferred.

For problems with UF APPS or connectivity (WIFI), please contact the UF Help Desk at [http://helpdesk.ufl.edu/](http://helpdesk.ufl.edu/), or call 352-392-4357.

## TEXTBOOK:

We will make occasional use of the below textbooks, both available free and online. Readings from these textbooks will be posted in Canvas.

1. **VanderPlas, J. (2016).** _Python Data Science Handbook: Essential Tools for Working with Data._ O'Reilly Media, Inc.  
   Available online at: [https://jakevdp.github.io/PythonDataScienceHandbook/](https://jakevdp.github.io/PythonDataScienceHandbook/)  
   This text is required and available for free online.

2. **VanderPlas, J. (2016).** _A Whirlwind Tour of Python._ O'Reilly Media, Incorporated.  
   Available online at: [https://jakevdp.github.io/WhirlwindTourOfPython/](https://jakevdp.github.io/WhirlwindTourOfPython/)  
   This text is required and available for free online.

## OFFICE HOURS

I have standing office hours on Wednesdays from 1-3 PM. No appointment is necessary. If you wish to reserve a specific time, you may use this link: [Office Hours Booking](https://outlook.office365.com/owa/calendar/OfficeHoursJoelDavis@uflorida.onmicrosoft.com/bookings/) (also available in Canvas) to reserve preferred times. You need to be logged in to a UF account (VPN or Microsoft 360) to book. When reserving time, you may see times available at other times of the week. If these are open and available to book, you are free to use that tool to reserve a meeting at those times. Please use the notes section of the reservation to send me any detail regarding the topic if you feel that is needed. It is fine, and even nice, to just come and say hello. You don't need a burning reason to book a chat. I assume the office hours booked 1-on-1 are in person, in my office. But if you prefer to meet online or outside, mark that in the notes. If you would like to meet via Zoom/Teams, block the time and send a meeting invite in Microsoft Teams or Zoom.

Given the online nature of this class, I will post occasional evening and weekend drop-in office hours on Zoom. I will use announcements to let you know the time and Zoom link.

## INSTRUCTOR COMMUNICATION

The best way to get a hold of me is via email or Canvas messages. It is important when you email about an issue that you tell me a little bit about yourself, at a minimum, just include the class number. I try to answer all emails within 24 hours during the week. On weekends, it will take longer.

# ACADEMIC POLICIES

## IMPORTANT DATES

*The instructor reserves the right to change the content of the course material if needed due to postponement of class caused by inclement weather, instructor illness, etc., or due to the pace of the course.*

## ATTENDANCE, MAKEUP EXAMS, MISSED WORK

Students are responsible for satisfying all academic objectives as defined by the professor.

In general, acceptable reasons for failure to participate in class include illness, serious family emergencies, special curricular requirements (e.g., judging trips, field trips, professional conferences), military obligation, severe weather conditions, religious holidays, and participation in official university activities such as music performances, athletic competition, or debate. Absences from class for court-imposed legal obligations (e.g., jury duty or subpoena) must be excused. Other reasons also may be approved. Students shall be permitted a reasonable amount of time to make up the material or activities covered in their absence.

There are no make-ups for missed exams or quizzes related to an unexcused absence.

Students cannot participate in the class unless they are registered officially or approved to audit with evidence of having paid audit fees. The Office of the University Registrar provides official class rolls to instructors.

## HONOR CODE REMINDER

UF students are bound by The Honor Pledge which states, “We, the members of the University of Florida community, pledge to hold ourselves and our peers to the highest standards of honor and integrity by abiding by the Honor Code. On all work submitted for credit by students at the University of Florida, the following pledge is either required or implied: “On my honor, I have neither given nor received unauthorized aid in doing this assignment.” The Honor Code ([http://www.dso.ufl.edu/sccr/process/student-conduct-honorcode/](http://www.dso.ufl.edu/sccr/process/student-conduct-honorcode/)) specifies several behaviors that are in violation of this code and the possible sanctions. Furthermore, you are obligated to report any condition that facilitates academic misconduct to appropriate personnel. If you have any questions or concerns, please consult with the instructor or TAs in this class.

## ASSURANCE OF LEARNING

Each program at the Warrington College of Business Administration has developed goals and objectives that express the most valued skills and knowledge that students should be able to demonstrate upon completion of the total learning experiences in that program. The following goals and objectives are specifically mapped onto this course:

- **Goal 1:** Demonstrate competency in and across business disciplines.
  - (1A) Demonstrate knowledge and understanding of elements of economics, finance, accounting, marketing.
  - (1B) Demonstrate proficiency in the use of business-related software applications.
- **Goal 2:** Apply appropriate problem-solving and decision-making skills.
  - (2A) Specify and implement a framework for identifying a business problem and develop alternative solutions.

## AI COURSE CONTENT

Each program at the University of Florida designated as an AI course has Student Learning Outcomes (SLOs) that describe the knowledge, skills, and attitudes that students are expected to acquire throughout the program.

This course fits into the UF AI Category "Build AI". In this course, students will: Evaluate & Create AI: Higher-order thinking skills (e.g., evaluate, appraise, predict, design) with AI applications. AI course content is over 50 percent.

This course has the following identified Student Learning Outcomes, with the corresponding week they are assessed:

- **SLO1:** Identify, describe, and/or explain the components, requirements, and/or characteristics of AI. (Weeks 3, 4, 6-13, simulation 1)
- **SLO2:** Recognize, identify, describe, define, and/or explain applications of AI in multiple domains. (Weeks 6-13, simulation 2)
- **SLO3:** Select and/or utilize AI tools and techniques appropriate to a specific context and application. (Weeks 6, 8, 9, 10, Week 13, simulation 2)
- **SLO5:** Assess the context-specific value or quality of AI tools and applications. (Weeks 8, 9, 10, 11, 12, 13, simulation 2)

When you see these noted in the syllabus, in the schedule, or written somewhere in the course materials- don't panic. These designations are for the university, they don't have any direct impact on your grade. If you have questions, let me know!

\newpage
# COURSE STRUCTURE

## SCHEDULE
| Week    | Date       | Content                                                     |
|:--------|:-----------|:------------------------------------------------------------|
| Week 0  | 2025-05-12 | **Getting Started**                                         |
| Week 1  | 2025-05-12 | **Python Basics:** Data Types and Variables                 |
| Week 2  | 2025-05-19 | **Python Basics:** Control & Loops, Functions               |
| Week 3  | 2025-05-26 | **Managing Data:** Pandas; numpy; importing data (SLO 1)    |
| Week 4  | 2025-06-02 | **Managing Data:** Missing Data; aggregating data           |
| Week 5  | 2025-06-09 | **Data Visualization:** Matplotlib; seaborn                 |
| Week 6  | 2025-06-16 | **Mid Term**                      |
| Week 7  | 2025-06-30 | **Analytics and AI Introduction**: validation (SLO 1, 2)    |
| Week 8  | 2025-07-07 | **Supervised Learning:** Regression & Trees (SLO 1, 2)      |
| Week 9  | 2025-07-14 | **Supervised Learning:** Classification (SLO 1, 2)          |
| Week 10 | 2025-07-21 | **Unsupervised Learning:** Clustering (SLO 1, 2)            |
| Week 11 | 2025-07-28 | **Reinforcement Learning Examples** (SLO 1, 2)              |
| Week 12 | 2025-07-28 | **Generative AI**                                           |
|         | 2025-08-04 | **Final exam**                                      |

Note Week 11 and 12 timing and due dates.  

## GRADING AND DATES DETAIL
| Date Assigned   | Date Due   | Activity              |   Points |
|:----------------|:-----------|:----------------------|---------:|
| 2025-05-12      | 2025-05-26 | Introduction. Say hi! |       5  |
| 2025-05-12      | 2025-05-26 | Course Intro Survey   |       5  |
| 2025-05-12      | 2025-05-26 | Install Python        |       10 |
| 2025-05-19      | 2025-05-26 | Quiz Week 2           |       50 |
| 2025-05-26      | 2025-06-02 | Quiz Week 3           |       50 |
| 2025-06-02      | 2025-06-09 | Quiz Week 4           |       50 |
| 2025-06-09      | 2025-06-16 | Quiz Week 5           |       50 |
| 2025-06-16      | 2025-06-23 | Simulation Exercise 1 |       40 |
| 2025-06-16      | 2025-06-23 | Midterm Weeks 1-6     |      250 |
| 2025-07-07      | 2025-07-14 | Quiz Week 8           |       50 |
| 2025-07-14      | 2025-07-21 | Quiz Week 9           |       50 |
| 2025-07-21      | 2025-07-28 | Quiz Week 10          |       50 |
| 2025-07-28      | 2025-08-04 | Quiz Week 11          |       50 |
| 2025-07-28      | 2025-08-06 | Quiz Week 12          |       50 |
| 2025-07-28      | 2025-08-06 | Simulation Exercise 2 |       40 |
| 2025-07-28      | 2025-08-06 | Final Practice        |       50 |
| 2025-08-04      | 2025-08-07 | Final Exam Weeks 7+   |      250 |



| **Grade** | **Score (in percent)** |
|-----------|------------------------|
| A         | 93.0 or above           |
| A-        | 92.9-90                 |
| B+        | 89.9-86.6               |
| B         | 86.5-83                 |
| B-        | 82.9-80                 |
| C+        | 79.9-76.6               |
| C         | 76.5-73                 |
| C-        | 72.9-70                 |
| D+        | 69.9-66.6               |
| D         | 66.5-63                 |
| D-        | 62.9-60                 |
| E         | Less than 60            |
: Final Grade Calculation {#tbl-letters}

## LECTURES

You will watch prerecorded course lectures within the course website pages. You will be responsible for all material presented in lectures. Lectures occasionally will be used to clarify and summarize the text, but will also include material not covered in the text. Please note that exam and assignment questions may come from material discussed verbally in the lecture. Additional videos may be posted throughout the course to answer student questions. The content of these will not be on the exams. Optional videos will be clearly labeled in the video title, the announcement, or the discussion post. If it is not labeled optional, questions in the exams may draw from the video. The first 6 weeks of the course cover the basics of using Python for data analysis, and the last 7 weeks cover more advanced topics in analytics and AI. Planned gaps in the schedule are for catching up and holidays/breaks.


## QUIZZES, SIMULATIONS AND EXAM DETAIL

**NOTE:** The number and weight of the assignments may be reduced during the semester at the discretion of the instructor. If a quiz or assignment is removed, the points for that assignment are also removed and are no longer considered when calculating the final grade. The final exam is harder than the midterm and the quizzes, so it is advisable to go into the final exam with a very good grade.

### SIMULATIONS

The simulation exercises test your understanding of the material to that date in the course. The first exercise has more coding, while the second exercise is almost exclusively related to testing your knowledge, understanding, and application of the analytics and AI approaches discussed in the lectures.

**Note on Grading the Simulation Assignments:** This simulation is intentionally challenging and designed to stretch your thinking. To ensure the grading reflects effort and relative mastery rather than absolute perfection, final scores will be curved based on the top 25% of performers. The average score of that top quartile will be mapped to full credit (40 points), and all other scores will be scaled proportionally. This approach ensures fairness while maintaining high standards. In practical terms this means when receiving your grade for this exercise, you should not panic. Once the exercise is complete, the curve will be calculated. The grades and the mapping used to generate them will be posted. 

### WEEKLY QUIZ

Most weeks of the course have a quiz. The quiz is open book, open notes, and untimed. Each quiz can be taken twice, and the highest score is retained. The due date for the quizzes (always the same each week) is posted on Canvas. I offer a 2-day automatic "grace" period for every quiz. This is intended to be used for emergencies only. The quiz is due on the due date. Without penalty and without approval, you can turn it in up to 2 days late. Keep in mind, of course, that were something to occur during the grace period, this would not be an adequate reason for an extension. You will need to show that you were not able to complete the quiz on time by the original due date, and that the 2-day grace period was inadequate to recover from that incident or problem and take the quiz. I believe these situations will be extremely rare.

At the end of the course, the 2 quizzes with the lowest grade will be dropped (not counted).

The quizzes in this course are designed to give you feedback on your current level of understanding. Many of the questions on the quiz have additional details and feedback available when the wrong/right answer is chosen. Be sure to read this after you have completed the quiz. This is important even if you scored very well; the additional details will help solidify your understanding of the material.

A word about late or missing quizzes: I understand that sometimes life, minor illness, other classes, and just plain mistakes are made, and a quiz is missed or completed late. I don't want to be the judge and jury of your misfortune. Sometimes bad things happen. The dropped quizzes and automatic grace period of 2 days per quiz allow you the privacy and flexibility to prioritize without worrying about my judgment or having one mistake result in a major grade impact. This grading does not remove an opportunity to make up a quiz due to an excused absence (see below), but given the generous "drop 2" policy and 2 days grace for grading, I would assume these are rare. The quizzes are open for 7 days; students who anticipate issues with conflicting activities should complete the quizzes earlier in the week. I believe, and hope you agree, this policy is clear, fair, and flexible. I ask in return that if you truly need an exception beyond this built-in flexibility, that you are clear and honest about that need.

Some of the questions for the quizzes are from a question pool. You should not expect second attempts at a quiz to be identical. On a retake, the questions may change. The new questions from the pool may look very similar to the first quiz questions. It is critical if you want to improve your grade that you read and complete each question again carefully, and not just plug in your answers from your first quiz attempt.

Throughout the course, you’ll encounter occasional ungraded survey-style questions—typically placed at the end of quizzes or activities. These questions are worth zero points and will **not impact your grade.** Their purpose is to give you a chance to reflect on your learning and to help me (your instructor) gauge how the class is progressing.

Your responses help identify what concepts are clear, what might need more explanation, and how I can improve the course in real time. While optional, your honest input is greatly appreciated and contributes to making this a more responsive and effective learning experience for everyone.

### MIDTERM AND FINAL EXAM

The midterm exam will be drawn evenly from all lectures, worksheets, and readings that occurred up to that point in the course (Weeks 1-6). The final exam covers all the material after the midterm to the end of the course. It does not test material from prior to the midterm, but it is important to note that much of the code and analytics post-midterm is built on that earlier learning. You are responsible for all assigned material. Students should have a notebook up and running for the exam to assist with validating answers to code completion problems. The exams are proctored using Honorlock. Students are not permitted to use the internet or work with others during the exams.

**MIDTERM EXAM:** The exam will be open and available to take anytime during the date range in Canvas. This may change slightly from this syllabus if we are behind or some event causes a delay. 

**FINAL EXAM:** The exam will be open and available to take anytime during the date range in Canvas. The dates in this syllabus are the current planned open and close dates for the exam, but Canvas should be your guide. 

### COLLABORATION

Writing code and performing data analytics is often a collaborative exercise. You are free to discuss on Canvas or elsewhere any materials from the lectures or workbooks. Quizzes, simulations, and exams are individual efforts only. Please do not post answers or solutions from these in the forums or elsewhere online.

#### Use of Generative AI tools or other AI tools

You are permitted to use generative AI tools (such as ChatGPT, GitHub Copilot, or similar technologies) for most course activities, including the graded quizzes, exercises, and assignments. However, AI tools may not be used during the midterm or final exam, which are intended to assess your individual understanding.

# UNIVERSITY POLICIES

## ACCOMMODATIONS FOR STUDENTS WITH DISABILITIES
Students with disabilities who experience learning barriers and would like to request academic accommodations
should connect with the disability Resource Center by visiting https://disability.ufl.edu/
students/get-started/. It is important for students to share their accommodation letter with their
instructor and discuss their access needs, as early as possible.

## ONLINE COURSE EVALUATION PROCESS
Students are expected to provide professional and respectful feedback on the quality of instruction in
this course by completing course evaluations online via GatorEvals. Guidance on how to give feedback
in a professional and respectful manner is available at https://gatorevals.aa.ufl.edu/students/.
Students will be notified when the evaluation period opens, and can complete evaluations through the
email they receive from GatorEvals, in their Canvas course menu under GatorEvals, or via https:
//ufl.bluera.com/ufl/. Summaries of course evaluation results are available to students at https:
//gatorevals.aa.ufl.edu/public-results/.

## CLASS RECORDING
Students are allowed to record video or audio of class lectures. However, the purposes for which these
recordings may be used are strictly controlled. The only allowable purposes are (1) for personal educational
use, (2) in connection with a complaint to the university, or (3) as evidence in, or in preparation for,
a criminal or civil proceeding. All other purposes are prohibited. Specifically, students may not publish
recorded lectures without the written consent of the instructor.

A “class lecture” is an educational presentation intended to inform or teach enrolled students about a particular
subject, including any instructor-led discussions that form part of the presentation, and delivered
by any instructor hired or appointed by the University, or by a guest instructor, as part of a University of
Florida course. A class lecture does not include lab sessions, student presentations, clinical presentations
such as patient history, academic exercises involving solely student participation, assessments (quizzes,
tests, exams), field trips, private conversations between students in the class or between a student and the
faculty or lecturer during a class session.

Publication without permission of the instructor is prohibited. To “publish” means to share, transmit,
circulate, distribute, or provide access to a recording, regardless of format or medium, to another person
(or persons), including but not limited to another student within the same class section. Additionally, a
recording, or transcript of a recording, is considered published if it is posted on or uploaded to, in whole or
in part, any media platform, including but not limited to social media, book, magazine, newspaper, leaflet,
or third party note/tutoring services. A student who publishes a recording without written consent may
be subject to a civil cause of action instituted by a person injured by the publication and/or discipline
under UF Regulation 4.040 Student Honor Code and Student Conduct Code.

Should all or part of this class or open study sessions be offered via an online mechanism during this
semester, our sessions may be audio visually recorded for students in the class to refer back and for enrolled
students who are unable to attend live. Students who participate with their camera engaged or
utilize a profile image are agreeing to have their video or image recorded. If you are unwilling to consent
to have your profile or video image recorded, be sure to keep your camera off and do not use a profile image.
Likewise, students who un-mute during class and participate orally are agreeing to have their voices
recorded. If you are not willing to consent to have your voice recorded during these sessions, you will need
to keep your mute button activated and communicate exclusively using the ”chat” feature, which allows
students to type questions and comments live.


# CAMPUS RESOURCES

## HEALTH AND WELLNESS

**U Matter, We Care:** If you or someone you know is in distress, please contact [umatter@ufl.edu](mailto:umatter@ufl.edu), 352-392-1575, or visit the [U Matter, We Care website](https://umatter.ufl.edu) to refer or report a concern, and a team member will reach out to the student in distress.

**Counseling and Wellness Center:** Visit the [Counseling and Wellness Center website](https://counseling.ufl.edu) or call 352-392-1575 for information on crisis services as well as non-crisis services.

**Student Health Care Center:** Call 352-392-1161 for 24/7 information to help you find the care you need, or visit the [Student Health Care Center website](https://shcc.ufl.edu).

**University Police Department:** Visit the [UF Police Department website](https://police.ufl.edu) or call 352-392-1111 (or 9-1-1 for emergencies).

**UF Health Shands Emergency Room / Trauma Center:** For immediate medical care, call 352-733-0111 or go to the emergency room at 1515 SW Archer Road, Gainesville, FL 32608. Visit the [UF Health Emergency Room and Trauma Center website](https://ufhealth.org/emergency-room-trauma-center).

**GatorWell Health Promotion Services:** For prevention services focused on optimal well-being, including Wellness Coaching for Academic Success, visit the [GatorWell website](https://gatorwell.ufsa.ufl.edu) or call 352-273-4450.

## ACADEMIC RESOURCES

**E-learning technical support:** Contact the UF Computing Help Desk at 352-392-4357 or via e-mail at [helpdesk@ufl.edu](mailto:helpdesk@ufl.edu). [https://helpdesk.ufl.edu](https://helpdesk.ufl.edu)

**Career Connections Center:** Reitz Union Suite 1300, 352-392-1601. Career assistance and counseling services. [https://career.ufl.edu](https://career.ufl.edu)

**Library Support:** Various ways to receive assistance with respect to using the libraries or finding resources. [https://uflib.ufl.edu/find/ask](https://uflib.ufl.edu/find/ask)

**Teaching Center:** Broward Hall, 352-392-2010 or to make an appointment 352-392-6420. General study skills and tutoring.

**Writing Studio:** 2215 Turlington Hall, 352-846-1138. Help brainstorming, formatting, and writing papers.

**Student Complaints On-Campus:** Visit the Student Honor Code and Student Conduct Code webpage for more information. [https://sccr.dso.ufl.edu/policies/student-honor-code-student-conduct-code](https://sccr.dso.ufl.edu/policies/student-honor-code-student-conduct-code)

**On-Line Students Complaints:** View the [Distance Learning Student Complaint Process](https://phhp.ufl.edu/wordpress/files/2021/02/H3.-Student-Complaint-Procedures.pdf).


